In [15]:
import numpy as np
import time

In [16]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [17]:
# Compare in terns of execution performance
size = 10_000_000 # 10 Million data sets

# time measure of python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end =  time.time()
print(f"python list time = {end-start} seconds")

# time measure of numpy arrays - wecan see the substantial difference
np_arr = np.array(py_list)
start = time.time()
# Vectorization replaces loop
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")


python list time = 1.7114126682281494 seconds
numpy array time = 0.01781153678894043 seconds


In [19]:
# memory Occupation - comparation
import sys
print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes") # it has lot od metadata stored so extra memory is required

print(f"numpy array size = {np_arr.nbytes} bytes") # it has built-in mathematical functions for numerical computations

Python list size = 800000560000000 bytes
numpy array size = 40000000 bytes


In [29]:
# Create Numpy Arrays from Lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)
arr2 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

# 2D List
arr2D = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
['1' '2' '3' '4' '5' 'Prime'] <class 'numpy.ndarray'> <U11 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [37]:
# we can create numoy from scratch
arr1 = np.zeros((2, 3), dtype = "int64") # Here we pass the dimensions, prefill with zero values. int64 to convert from float to int values, it is dtype property for type casting
print(arr1, arr1.shape)

arr2 = np.ones((5, ))
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) # Prefil with particular value
print(arr3, arr3.shape)

arr4 = np.eye(3) # To create identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) # similar to range(start, end, step) , to create range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) # (start, end, totalValues) To create evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [42]:
# Properties of numpy arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) # we print numpy arrays dimensions = m * n
print(arr.size) # total elements
print(arr.dtype) # print the datatype
print(arr.ndim) # to print no.of dimension values - here we have taken 2D array
float_arr = arr.astype(np.float64) # Function for typecasting
print(float_arr, float_arr.dtype)

(2, 3)
6
int32
2
[[1. 2. 3.]
 [4. 5. 6.]] float64


In [48]:
# Operations on arrays
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2)) # This can be done if we have compactable no.of elements, i.e both arrays must have equal no.of elements
print(reshaped, reshaped.shape)

flattened = arr.flatten() # 2D => 1D array
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [56]:
# Indexing on normal plane 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr[0]) 
print(arr[4])

# Indexing in 2D array - Normal Indexing
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr1[1][1])

# Fancy Indexing
arr2 = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 3]
print(arr2[idx])

# Boolean Indexing
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3[arr3 > 3])
print(arr3[arr3 % 2 == 0])
print(arr3[arr3 % 2 != 0])

1
5
5
[1 2 4]
[4 5]
[2 4]
[1 3 5]


In [57]:
# Slicing in 1D array in numpy is similar to python list
arr = np.array([1, 2, 3, 4, 5]) # we pass [start, end, step]
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:]) # we get the entire array
print(arr[::2]) # we get alternate elements

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [59]:
# Copy vs View
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy() # To create a copy and the changes won't reflect in the original array
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [65]:
# Datatypes
arr = np.array([1, 2, 3, 4, 5])
print(arr, arr.dtype)

arr1 = np.array([1, 2, 3.14, 4, 5])
print(arr1, arr1.dtype)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, arr2.dtype)

arr3 = np.array([3 + 5j])
arr4 = np.array([2 + 3j])
print(arr3, arr3.dtype)
print(arr3 + arr4)
print(arr3 - arr4)

arr5 = np.array(["prime", {1,2,3}, 3.14]) # Heterogeneous data are converted to object type
print(arr5, arr5.dtype)

[1 2 3 4 5] int32
[1.   2.   3.14 4.   5.  ] float64
['1' '2' '3' '4' '5' 'prime'] <U11
[3.+5.j] complex128
[5.+8.j]
[1.+2.j]
['prime' {1, 2, 3} 3.14] object


In [70]:
# Multi-Dimensional Arrays
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)
print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

# Slicing in 2D Array
print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [7]:
import numpy as np
# 3D array
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]) # 2 * 3 * 2
print(arr3D, arr3D.shape)

# Indexing
print(arr3D[0, 1, 1])
print(arr3D[1, 1, 0])

# Slicing to extract a particular row or col
print(arr3D[:, 0, :]) # first row from both layers
print(arr3D[:, :, 0]) # first col from both layers
arr3D[:, 0, :] = 99 # data manipulation
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [10]:
# Vectorization - faster as compared to looping in python lists
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([6, 7, 8, 9, 10])
print(arr ** 2)
print(arr + 10)
print(arr + arr1)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [11]:
# Broadcasting
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr.shape)
print(arr1.shape)
print(arr + arr1)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [16]:
# Normalization
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean) / std_dev
print(normalized_arr)
print(mean) # mean = 0
print(std_dev) std_dev = 1

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [19]:
# Mathematical Functions - aggregation functions
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4


In [24]:
# Power Function
arr = np.array([1, 2, 3, 4, 5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [27]:
# log function
arr = np.array([1, 2, 3, 4, 5])
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [34]:
# Rounding Function
print(np.round(3.14))
print(np.ceil(3.14)) # Round off to upper values
print(np.floor(3.14)) # Round off to lower values
print(np.trunc(3.14)) # To cut the values after the decimal point

arr = np.array([1, 2, -8, 3, 4, -5, 2, -5])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[1 2 3 4 5 8]
[1 2 2 3 4 5 5 8]
